import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/utils/Provider";
import ToggleBackground from "@/components/ui/ToggleBackground.tsx/ToggleBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="p-0 m-0 box-border">
        <ToggleBackground>
          <Provider>{children}</Provider>
        </ToggleBackground>
      </body>
    </html>
  );
}
