import type { Metadata } from "next";
import "./globals.css";
import { Provider } from "@/utils/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="p-0 m-0 box-border">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
